# Generated by Django 4.1.7 on 2023-03-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
